CREATE DATABASE IF NOT EXISTS iter CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS iter_chat CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS iter_ai CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
