plugins {
    id 'iter.spring-app-conventions'
    id 'iter.kotlin-conventions'
}

description = 'iter'

dependencies {
    implementation project(':libs:core')
    implementation project(':libs:security')
    implementation project(':libs:storage')
    implementation project(':services:domain-api')
    implementation project(':services:delivery')
    implementation project(':services:notification')
    implementation project(':services:dispute')
    implementation project(':services:auth')
    implementation project(':services:payment')
    implementation project(':services:device')
    implementation project(':services:reservation')

    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.security
    implementation libs.spring.boot.starter.security.oauth2.client
    implementation libs.spring.boot.starter.validation
    implementation libs.spring.boot.starter.webmvc
    implementation libs.spring.boot.starter.mail

    implementation libs.bouncycastle.bcprov
    implementation libs.jjwt.api
    runtimeOnly libs.jjwt.impl
    runtimeOnly libs.jjwt.jackson
    implementation libs.springdoc.openapi.webmvc.ui

    implementation libs.spring.boot.starter.flyway
    runtimeOnly libs.flyway.mysql
    runtimeOnly libs.mysql.connector

    testImplementation libs.spring.boot.starter.data.jpa.test
    testImplementation libs.spring.boot.starter.security.test
    testImplementation libs.spring.boot.starter.security.oauth2.client.test
    testImplementation libs.spring.boot.starter.validation.test
    testImplementation libs.spring.boot.starter.webmvc.test
    testImplementation libs.spring.boot.starter.flyway.test
    testRuntimeOnly libs.h2
}
